name: cached_network_image
description: Flutter library to load and cache network images. Can also be used with placeholder and error widgets.
version: 0.4.1+1
author: Rene Floor <pub@renefloor.nl>
homepage: https://github.com/renefloor/flutter_cached_network_image

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_cache_manager:
    git:
      url: https://github.com/CaiJingLong/flutter_cache_manager.git
      ref: 38b368c80e34707c49b146132670ec7ccb3566b7

dev_dependencies:
  test: ^1.3.0
